### ISSUE TITLE
Lab 5#End to end user review by Jinsong Xie on Enter expense 

### ISSUE THREAD

**Issue by Mansteinvon** [Weilei424/Wallet-Watcher#34]
User story:Enter expense 

1 Unhandle exception 
    if enter the date in a format not accepted by ledgeritem Dataparser method, the exception is thrown though no handling at the expensdeinputform 
![addexpenseexceptionjpg](https://user-images.githubusercontent.com/36380930/227755103-0915e990-b33d-4253-bf39-8f6c4bf4db4d.jpg)

2 Negative amount 
     When amount enter is negative , the system should warn the user no negative amount allowed based on the logic of expense. Should not insert it into the database. 

![addexpense](https://user-images.githubusercontent.com/36380930/227755171-d88b6ec7-fc1d-4697-8dff-83069e610852.jpg)

   3 after successful entry of expense item, it should allow user to continue add more expense. Instead user have nothing allowed by go back to main menu and enter expense page again to add new expense 
      ![enterexpense](https://user-images.githubusercontent.com/36380930/227755135-71702649-f649-494f-a5cd-573fc73370af.jpg)

**Comment by Weilei424** [comment]
Good catch John, I'll fix this soon

**Comment by Weilei424** [comment]
Bug#1 and bug#3 are explained in User Mannual. If user follows the mannual, there won't be problem.

Bug#1 will be fixed by changing the date entry into a pop up date selector window.

Thank you.

**Comment by Mansteinvon** [comment]
To my end for bug #3, after I press submit button, the data entry window should not close though it close, could you verify it on your end

**Comment by Weilei424** [comment]
> 

You are correct, it seems this issue only happens to 'expense' page. I'll look into this. Thank you
