### ISSUE TITLE
Lab #5 End to End test 

### ISSUE THREAD

**Issue by MustafaSyed19** [Weilei424/Wallet-Watcher#35]
### Bugs discovered in end to end user testing:
Small Stories:  budget, earnings and misc tracker
**Issue # 1**: When the wrong date format is inputted, exception gets thrown but is not handled, tiny page stays open. Common issue with all pages
![bug3a](https://user-images.githubusercontent.com/122815859/227806475-685fcee9-95ea-4065-917c-52edb4bc8b7a.png)
![bug3](https://user-images.githubusercontent.com/122815859/227806477-604f3267-c0df-47be-84a0-7087a54e866d.png)
**Improvement:** Increase constraints so that user can't enter dates like this 

**Issue # 2**: For misc earnings the nav is left open when we are accessing the misc earnings page 
![bug4](https://user-images.githubusercontent.com/122815859/227806518-736a112e-64b5-4789-86e3-6376fbeecdff.png)
**Improvement:** Dispose of the nav page when the button is clicked 

**Issue # 3:** Negative values can be inputted for earnings, expenses, budget, etc, also page bugs out not allowing you to enter multiple earnings: 

![bug 5](https://user-images.githubusercontent.com/122815859/227806555-6fa32e5b-a25e-4bab-8c1c-d87720e77bc0.png)

**Improvement:** add a verification to pages such that negative values cant be used, for the the other one it likely has something to do with the action listener for the forms (change action listener) 

**Issue # 4:** There's no exit button causing the user to have to input something to leave the page

![bug 6](https://user-images.githubusercontent.com/122815859/227806579-4e782d02-9055-4f8d-8ef1-77ae61966624.png)

**Improvement:** add an exit button to the forms

**Comment by Weilei424** [comment]
Hi Mustafa,

Issue#1 will not be fixed untill we find out a solution of different way of date input;
Issue#2 will be fixed soon, we have the same issue with other UI pages;
Issue#3 and issue#4 will be fixed soon, we will make changes to all  input forms;

Thank you
